package com.mayank.hotelbooking.exceptions;

public enum ExceptionType {
    HOTEL_ALREADY_EXISTS,
    HOTEL_NOT_FOUND,
    ROOM_NOT_FOUND,
    ROOM_ALREADY_EXISTS,
    ROOM_INVENTORY_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    PAYMENT_NOT_EXISTS,
    RESERVATION_ALREADY_EXISTS,
    RESERVATION_NOT_FOUND,
    RATE_CARD_ALREADY_EXISTS,
    RATE_CARD_NOT_FOUND
}
